# Generated by Django 5.0.1 on 2024-01-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='file',
            new_name='pdf_file',
        ),
    ]
